
### Create new game
POST http://localhost:8080/test_create HTTP/1.1
content-type: application/json

{
	"basketCount": 18,
	"players": [
		"Haloo",
		"Jing Jang",
		"Miikka"
	]
}

### Create another new game, as
POST http://localhost:8080/game HTTP/1.1
content-type: application/json

{
	"basketCount": 7,
	"players": [
		"Samu",
		"Ari"
	]
}

### Create/Edit course scores
PUT http://localhost:8080/game/1as HTTP/1.1
content-type: application/json

{
	"course": 2,
	"players": {
		"Samu": {
			"par": 3,
			"score": 5,
			"ob": 0
		},
		"Ari": {
			"par": 3,
			"score": 4,
			"ob": 0
		}
	}
}

### GET
GET http://localhost:8080/game/1as HTTP/1.1
content-type: text/plain

### GET
GET http://localhost:8080/game/1jmp HTTP/1.1
content-type: text/plain
